name: CI

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main, 'feature/**' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install requirements
        run: pip install -r requirements_dev.txt
      - name: Run flake8
        run: flake8 .
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install requirements
        run: pip install -r requirements_dev.txt
      - name: Run mypy
        run: mypy flake8_functions_names
  test:
    runs-on: ubuntu-latest
    needs: [lint, types]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install requirements
        run: pip install -r requirements_dev.txt
      - name: Install self
        run: pip install -e .
      - name: Run tests
        run: pytest .
